item_index:
    path:     /
    defaults: { _controller: "RoyalTodoBundle:Item:index" }
    methods:  GET
item_new:
    path:     /
    defaults: { _controller: "RoyalTodoBundle:Item:new" }
    methods:  [POST]

item_show:
    path:     /{id}
    defaults: { _controller: "RoyalTodoBundle:Item:show" }
    methods:  GET

item_edit:
    path:     /{id}
    defaults: { _controller: "RoyalTodoBundle:Item:edit" }
    methods:  [POST]

item_delete:
    path:     /{id}
    defaults: { _controller: "RoyalTodoBundle:Item:delete" }
    methods:  DELETE
